lzc-sdk-version: "0.1"
name: Kamifaka
package: cloud.lazycat.app.kamifaka
version: 1.8.0
homepage: https://github.com/Baiyuetribe/kamiFaka
author: Baiyuetribe
application:
  subdomain: kamifaka
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  public_path:
    - /
  routes:
    - /=http://kamifaka:8000/
services:
  kamifaka:
    image: docker.hlmirror.com/baiyuetribe/kamifaka:v1.8

    binds:
      - /lzcapp/var/db:/usr/src/app/database
locales:
    zh:
        name: "佰阅发卡"
        description: "开源发卡系统"
    zh_CN:
        name: "佰阅发卡"
        description: "开源发卡系统"
    en:
        name: "Kamifaka"
        description: "Open Source Digital Goods Distribution System"